blueprints/__init__.py
from .home import home
from .uploader import uploader

blueprints/home/__init__.py
from .blueprint import home

blueprints/home/blueprint.py
from flask import Blueprint, render_template, request
import psycopg2

import tensorflow as tf
import os
import random


home = Blueprint('home', __name__)

IMAGE_WIDTH, IMAGE_HEIGHT = 192, 192


def load_resize_save_image(path, filename):
    image = tf.io.read_file(path + "/" + filename)
    try:
        image = tf.image.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [IMAGE_WIDTH, IMAGE_HEIGHT])
        tf.keras.preprocessing.image.save_img(
            path + "/" + filename, image, data_format='channels_last')
    except:
        os.remove(path + "/" + filename)


@home.route('/',  methods=['POST', 'GET'])
def route_name():
    if request.method == 'GET':
        return render_template('home.html', feedback=False)
    else:
        name_of_image, category = request.form['text'].split(", ")
        print(name_of_image, category)

        src = "./uploads/" + name_of_image
        dst = "./new_classified_fruits/" + category + "/" + name_of_image
        # rename() function will rename all the files
        load_resize_save_image("./uploads", name_of_image)
        os.rename(src, dst)
        return render_template('home.html', feedback=True)

blueprints/uploader/__init__.py
from .blueprint import uploader

blueprints/uploader/blueprint.py
from flask import Blueprint, render_template, request, redirect, send_from_directory
from keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.mobilenet import preprocess_input
from werkzeug import secure_filename
import tensorflow as tf
import numpy as np
import os

UPLOAD_FOLDER = 'uploads'

model = tf.keras.models.load_model('models/model.h5')

uploader = Blueprint('uploader', __name__)

# IMAGE_SIZE = 100
IMAGE_SIZE = 192


@uploader.route('/uploader', methods=['GET', 'POST'])
def upload():
    # get file
    uploaded_file = request.files['file']

    # check if file is an image
    if uploaded_file.content_type != "image/jpeg":
        return redirect("/")

    # create path of image
    upload_image_path = os.path.join("uploads", uploaded_file.filename)

    # save image
    uploaded_file.save(upload_image_path)
    # classify image
    probability = classify(upload_image_path)
    return render_template('home.html', probability=probability, filename=uploaded_file.filename)


def classify(upload_image_path):

    # img = tf.io.read_file(upload_image_path)
    # img = tf.image.decode_jpeg(image, channels=3)
    img = image.load_img(
        upload_image_path, target_size=(IMAGE_SIZE, IMAGE_SIZE))
    img_array = image.img_to_array(img)
    expanded_image_array = np.expand_dims(img_array, axis=0)
    preprocessed_image = preprocess_input(
        expanded_image_array)  # Preprocess the image
    # image = tf.image.resize(image, [IMAGE_SIZE, IMAGE_SIZE])
    # image /= 255.0  # normalize to [0,1] range
    # image = tf.reshape(image, (1, IMAGE_SIZE, IMAGE_SIZE, 3))
    probability = model.predict(preprocessed_image)

    if probability[0][0] > probability[0][1] and probability[0][0] > probability[0][2]:
        return {"apple": round((probability[0][0] * 100), 2)}
    elif probability[0][1] > probability[0][0] and probability[0][1] > probability[0][2]:
        return {"banana": round((probability[0][1] * 100), 2)}
    else:
        return {"cherry": round((probability[0][2] * 100), 2)}


@uploader.route('/uploader/<filename>')
def send_file(filename):
    return send_from_directory("uploads", filename)

main.py
from flask import Flask, render_template
from blueprints import *

app = Flask(__name__)
app.register_blueprint(home)
app.register_blueprint(uploader)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001, debug=True)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Fruits predictor</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="shortcut icon" type="image/png" href="static/images/fav.jpg" />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <!-- CSS -->
    <link href="static/css/style.css" rel="stylesheet" />
  </head>
  <body class="text-center">
    {% block content%} {% endblock %}

    <script src="static/js/jquery-3.4.1.min.js"></script>
    <script src="static/js/index.js"></script>
    <script type="text/javascript"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %} {% block content %}
<div style="margin-top:50px">
  <div></div>
  {% if feedback %}
  <div class="alert alert-success fade show" role="alert" style="margin:20px 100px">
    <strong>Thank you for your feedback!</strong> Our model will be improved soon.
  </div>
  {% endif%}

  {% if probability %}
  <div style="width:210px;background-color:#fff;padding-bottom:10px; display:inline-block;padding-bottom:10px;margin-bottom:10px;border-radius:100px;border:solid 10px rgb(214, 69, 65);" class="animated bounce"> 
    {% if probability.apple %} 
    <div class="item">
      <div class="apple"></div>
      <div style="padding-top:120px;" class="text-percentage">{{probability.apple}}%</div>
    </div>
    {% endif%}
    {% if probability.banana %} 
    <div class="item">
      <div class="banana"></div>
      <div class="banana-line"></div>
   </div>
    <div class="text-percentage">{{probability.banana}}%</div>
    {% endif%}
    {% if probability.cherry %} 
    <div class="item" style="position:relative;">
      <div class="cherry cherry1"></div>
      <div class="cherry cherry2"></div>
      <div class="cherry-join"></div>
    </div>
    <div class="text-percentage">{{probability.cherry}}%</div>
    {% endif%}
  </div>
    {% if (probability.cherry or probability.banana) %} 
    <form action="/" method="POST" enctype="multipart/form-data">
      <input name="text" value="{{filename}}, apple" class="d-none">
      <input type="submit" class="wrong correction_btn" value="Was it a apple?" id="snd" style=""/>
    </form>
    {% endif%}
    {% if (probability.apple or probability.cherry) %} 
    <form action="/" method="POST" enctype="multipart/form-data" style="margin-top:10px">
      <input name="text" value="{{filename}}, banana" class="d-none">
      <input type="submit" class="wrong correction_btn" value="Was it a banana?" id="snd" style=""/>
      </form>
    {% endif%}
    {% if (probability.apple or probability.banana) %} 
    <form action="/" method="POST" enctype="multipart/form-data" style="margin-top:10px">
      <input name="text" value="{{filename}}, cherry" class="d-none">
      <input type="submit" class="wrong correction_btn" value="Was it a cherry?" id="snd" style=""/>
      </form>
    {% endif%}

  {% endif%}


  {% if filename %}


  <img
    class="pred_img"
    style="max-height:200px; margin:50px; border-radius:100px;border:solid 10px rgb(214, 69, 65);"
    src="{{ url_for('uploader.send_file', filename=filename)}}"
  />

  {% else %}
  <div style="background:white;display:inline-block; margin: 200px 0px 30px ; border-radius:100px;padding:10px 30px;border:solid 10px rgb(214, 69, 65);">
    <div class="item">
      <div class="apple"></div>
    </div>
  
    <div class="item">
      <div class="banana"></div>
      <div class="banana-line"></div>
   </div>
  
    <div class="item" style="position:relative;">
      <div class="cherry cherry1"></div>
      <div class="cherry cherry2"></div>
      <div class="cherry-join"></div>
    </div>
  </div>


  {% endif %}

  <form action="/uploader" method="POST" enctype="multipart/form-data">
    <input type="file" id="file" name="file" />
    <div class="new_Btn" style="width: 180px;">
      <div class="text-select">Select a picture</div> 
      <div class="spinner-border text-dark d-none" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
    </div>
    <input type="submit" class="button" value="Send" id="send" />
  </form>
</div>
{% endblock %}

templates/upload.html
{% extends "base.html" %} {% block content %}
<div>upload</div>
{% endblock %}